import { motion } from "framer-motion"

interface StartupScoreProps {
  scoreData?: {
    overall: number
    metrics: { name: string; score: number }[]
  }
}

export default function StartupScore({ scoreData }: StartupScoreProps) {
  const metrics = scoreData?.metrics || [
    { name: "Market Potential", score: 88 },
    { name: "India Fit", score: 92 },
    { name: "Investor Appeal", score: 80 },
    { name: "Competition", score: 75 },
    { name: "Execution Difficulty", score: 65 },
  ]

  const overallScore = scoreData?.overall ?? 84

  let badgeText = "STRONG BUY/SEED"
  if (overallScore >= 85) {
    badgeText = "STRONG BUY/SEED"
  } else if (overallScore >= 75) {
    badgeText = "BUY/EARLY-STAGE"
  } else if (overallScore >= 60) {
    badgeText = "HOLD/NEUTRAL"
  } else {
    badgeText = "HIGH RISK/AVOID"
  }

  return (
    <section 
      id="pricing"
      className="py-24 px-6 md:px-12 max-w-5xl mx-auto scroll-mt-20 relative z-10"
    >
      <div className="text-center mb-16">
        <motion.h2
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
          className="text-3xl md:text-4xl font-bold uppercase tracking-tight text-foreground"
        >
          PitchIQ Score
        </motion.h2>
        <motion.p
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5, delay: 0.1 }}
          className="text-muted-foreground mt-2 font-light text-base"
        >
          Quantitative startup assessment index generated by consensus agents.
        </motion.p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-10 items-center">
        {/* Large Score Gauge */}
        <motion.div
          initial={{ opacity: 0, scale: 0.9 }}
          whileInView={{ opacity: 1, scale: 1 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="bg-secondary/15 border border-border/40 rounded-xl p-8 flex flex-col items-center justify-center text-center h-full relative"
          style={{
            boxShadow: "inset 0 1px 0 0 rgba(255,255,255,0.03)",
          }}
        >
          <div className="absolute inset-0 bg-primary/[0.01] rounded-xl pointer-events-none" />

          <h3 className="text-sm font-semibold uppercase tracking-widest text-muted-foreground mb-6">
            Overall Rating
          </h3>

          <div className="relative w-40 h-40 flex items-center justify-center">
            {/* SVG Radial Gauge */}
            <svg className="absolute w-full h-full transform -rotate-90" viewBox="0 0 160 160">
              {/* Background circle */}
              <circle
                cx="80"
                cy="80"
                r="70"
                className="stroke-neutral-800"
                strokeWidth="6"
                fill="transparent"
              />
              {/* Animated progress circle */}
              <motion.circle
                cx="80"
                cy="80"
                r="70"
                className="stroke-primary"
                strokeWidth="6"
                fill="transparent"
                strokeDasharray="440"
                initial={{ strokeDashoffset: 440 }}
                animate={{ strokeDashoffset: 440 - (440 * overallScore) / 100 }}
                transition={{ duration: 1.2, ease: "easeOut" }}
                strokeLinecap="round"
              />
            </svg>

            {/* Pulsing glow ring inside */}
            <div className="absolute inset-5 rounded-full border border-primary/10 bg-primary/5 animate-pulse" />
            
            <div className="flex flex-col items-center relative z-10">
              <span className="text-5xl font-bold text-foreground font-sora">{overallScore}</span>
              <span className="text-xs text-muted-foreground font-mono mt-1">/ 100</span>
            </div>
          </div>

          <span className="text-primary font-bold uppercase tracking-wider text-xs bg-primary/10 border border-primary/30 px-4 py-1.5 rounded-full mt-8 font-mono">
            {badgeText}
          </span>
        </motion.div>

        {/* Individual Metrics Progress Bars */}
        <div className="lg:col-span-2 bg-secondary/10 border border-border/40 rounded-xl p-8 flex flex-col gap-6">
          <h3 className="text-sm font-bold uppercase tracking-widest text-muted-foreground border-b border-border/20 pb-4">
            Validation Metrics
          </h3>

          <div className="flex flex-col gap-5">
            {metrics.map((met, idx) => (
              <div key={idx} className="flex flex-col gap-2">
                <div className="flex justify-between items-center text-sm">
                  <span className="text-foreground/90 font-light">{met.name}</span>
                  <span className="font-mono text-primary font-semibold">{met.score}%</span>
                </div>
                <div className="h-2 bg-black/40 rounded-full overflow-hidden border border-border/30">
                  <motion.div
                    initial={{ width: "0%" }}
                    whileInView={{ width: `${met.score}%` }}
                    viewport={{ once: true }}
                    transition={{ duration: 1, ease: "easeOut", delay: idx * 0.1 }}
                    className="h-full bg-primary"
                  />
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  )
}
